vim.lsp.set_log_level("off")
-- vim.lsp.set_log_level("debug")

require("dvim.modules.lsp.mappings")

require("dvim.modules.lsp.lang.ansible")
require("dvim.modules.lsp.lang.awk")
require("dvim.modules.lsp.lang.bash")
require("dvim.modules.lsp.lang.clang")
-- require("dvim.modules.lsp.lang.csharp")
require("dvim.modules.lsp.lang.css")
require("dvim.modules.lsp.lang.docker")
require("dvim.modules.lsp.lang.dot")
require("dvim.modules.lsp.lang.elixir")
require("dvim.modules.lsp.lang.html")
require("dvim.modules.lsp.lang.glsl")
require("dvim.modules.lsp.lang.godot")
require("dvim.modules.lsp.lang.javascript")
require("dvim.modules.lsp.lang.jq")
require("dvim.modules.lsp.lang.json")
require("dvim.modules.lsp.lang.lua")
require("dvim.modules.lsp.lang.markdown")
require("dvim.modules.lsp.lang.nix")
require("dvim.modules.lsp.lang.php")
require("dvim.modules.lsp.lang.python")
require("dvim.modules.lsp.lang.rust")
require("dvim.modules.lsp.lang.svelte")
require("dvim.modules.lsp.lang.terraform")
require("dvim.modules.lsp.lang.typescript")
require("dvim.modules.lsp.lang.vim")
require("dvim.modules.lsp.lang.xml")
require("dvim.modules.lsp.lang.yaml")
